// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nnhdsugvixutbgtngflv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5uaGRzdWd2aXh1dGJndG5nZmx2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzMDIxMDksImV4cCI6MjA3Mzg3ODEwOX0._43p5IMULpJVbvHE33E2GlwMYjD-FpdTtNJd2mo3ZP0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});